export const ROLES = [
  'ASISTENTE',
  'AUTOR',
  'EVALUADOR',
  'ORGANIZADOR_CIENTIFICO',
  'ADMINISTRADOR',
] as const;

export type Rol = (typeof ROLES)[number];

export const TIPOS_TRABAJO = [
  'TRABAJO_CIENTIFICO',
  'RELATO_DE_EXPERIENCIA',
  'PROPUESTA_TALLER',
] as const;

export const TIPOS_ACTIVIDAD = [
  'MESA_TEMATICA',
  'MESA_REDONDA',
  'POSTER',
  'TALLER',
  'CONFERENCIA',
] as const;

export const METODOS_PAGO = ['TRANSFERENCIA', 'TARJETA', 'EFECTIVO'] as const;

export const ESTADOS_PAGO = ['PENDIENTE', 'APROBADO', 'RECHAZADO'] as const;

export const ESTADOS_TRABAJO = [
  'BORRADOR',
  'ENVIADO',
  'PRECHECK_OK',
  'PRECHECK_OBSERVADO',
  'EN_EVALUACION',
  'PENDIENTE_APROBACION_COMITE',
  'APROBADO',
  'OBSERVADO_EVALUACION',
  'RECHAZADO',
  'NOTIFICADO',
  'PROGRAMADO',
] as const;
