package ar.edu.unlp.jyaa.grupo1.modelo;

public enum EstadoTrabajo {
  BORRADOR,
  ENVIADO,
  PRECHECK_OK,
  EN_EVALUACION,
  PENDIENTE_APROBACION_COMITE,
  APROBADO,
  APROBADO_CON_CORRECCIONES,
  RECHAZADO,
  NOTIFICADO,
  PROGRAMADO
}
